GET http://localhost:3000

### Register User 
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "your_password",
  "role_id": 1
}

### Login User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "your_password"
}

### Shop item
POST http://localhost:3000/api/shop_items
Content-Type: application/json

{
  "name": "Product Name",
  "price": 29.99,
  "description": "Product description goes here",
  "image": "path/to/image.jpg",
  "item_type_id": 1
}

### All Shop Items
GET http://localhost:3000/api/shop_items



