GET http://localhost:3000

### Register User 
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "your_password",
  "role_id": 1
}

### Login User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "your_password"
}

### Shop item
POST http://localhost:3000/api/shop_items
Content-Type: application/json

{
  "name": "Product Name",
  "price": 29.99,
  "description": "Product description goes here",
  "image": "path/to/image.jpg",
  "item_type_id": 1
}

### All Shop Items
GET http://localhost:3000/api/shop_items

### Shop Item
GET http://localhost:3000/api/shop_items/1

### Delete Shop Item 
DELETE http://localhost:3000/api/shop_items/1

### post orders
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "user_id": 1,
  "shop_item_id": 123,
  "quantity": 2,
  "total_price": 30.5,
  "status": "pending"
}

### all orders
GET http://localhost:3000/api/orders

### single order
GET http://localhost:3000/api/orders/2

### order by user
GET http://localhost:3000/api/orders/user/1

### gauti visas roles
GET http://localhost:3000/api/user_roles






